#!/usr/bin/env python3

import sys
import os
from google import genai
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

api = os.environ.get("gemini_api")
prompt = " ".join(sys.argv[1:])
client = genai.Client(api_key=api)
console = Console()

if prompt == '':
    console.print("[red]Bro you typed nothing[/red]")
    sys.exit()

res = client.models.generate_content(
    model='gemini-3.5-flash',
    contents=prompt
    )
with console.pager(styles=True):
    console.print(Panel(Markdown(res.text), title='Gemini'))


